// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240930064328_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Estacionamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PrecoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Placa");

                    b.HasIndex("PrecoId");

                    b.ToTable("Estacionamentos");
                });

            modelBuilder.Entity("Domain.Preco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FimVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HoraAdicional")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoraInicial")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Precos");
                });

            modelBuilder.Entity("Domain.Estacionamento", b =>
                {
                    b.HasOne("Domain.Preco", "Preco")
                        .WithMany()
                        .HasForeignKey("PrecoId");

                    b.Navigation("Preco");
                });
#pragma warning restore 612, 618
        }
    }
}
